/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ImageProc */

#ifndef _Included_com_ImageProc
#define _Included_com_ImageProc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ImageProc
 * Method:    grayProc
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_ImageProc_grayProc
  (JNIEnv *, jclass, jintArray, jint, jint);

JNIEXPORT jfloatArray JNICALL Java_com_ImageProc_getDataProc
  (JNIEnv *, jclass, jintArray, jint, jint);
#ifdef __cplusplus
}
#endif
#endif
